"use client";

import { useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { MoreHorizontal, Plus, Search, ShieldCheck, UserPlus, X } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

type Expert = { id: number; name: string; field: string; domain: string; plan: string; inquiries: number; status: "active" | "draft" | "inactive"; members: { name: string; role: "Owner" | "Assistant" }[] };
const seedExperts: Expert[] = [
  { id: 1, name: "김인만", field: "부동산", domain: "kim-inman.experty.kr", plan: "Free", inquiries: 4, status: "active", members: [{ name: "김인만", role: "Owner" }, { name: "김민서", role: "Assistant" }] },
  { id: 2, name: "김덕진", field: "IT·AI", domain: "kim-deokjin.experty.kr", plan: "Pro", inquiries: 18, status: "active", members: [{ name: "김덕진", role: "Owner" }] },
  { id: 3, name: "채상욱", field: "경제·부동산", domain: "chaesangwook.experty.kr", plan: "Basic", inquiries: 7, status: "draft", members: [{ name: "채상욱", role: "Owner" }] },
];

const statusClass = { active: "bg-emerald-50 text-emerald-600", draft: "bg-amber-50 text-amber-600", inactive: "bg-surface-2 text-ink-400" };
const statusLabel = { active: "운영 중", draft: "준비 중", inactive: "비활성" };

export default function PlatformAdminPage() {
  const [experts, setExperts] = useState(seedExperts); const [selectedId, setSelectedId] = useState(1); const [newOpen, setNewOpen] = useState(false); const [memberOpen, setMemberOpen] = useState(false); const [query, setQuery] = useState(""); const [expertName, setExpertName] = useState(""); const [memberName, setMemberName] = useState("");
  const selected = experts.find((expert) => expert.id === selectedId) ?? experts[0]; const visible = experts.filter((expert) => `${expert.name} ${expert.field}`.includes(query));
  function addExpert() { if (!expertName.trim()) return; const slug = expertName.trim().replaceAll(" ", "-").toLowerCase(); const created: Expert = { id: Date.now(), name: expertName.trim(), field: "미설정", domain: `${slug}.experty.kr`, plan: "Free", inquiries: 0, status: "draft", members: [{ name: expertName.trim(), role: "Owner" }] }; setExperts((current) => [...current, created]); setSelectedId(created.id); setExpertName(""); setNewOpen(false); }
  function addMember() { if (!memberName.trim()) return; setExperts((current) => current.map((expert) => expert.id === selected.id ? { ...expert, members: [...expert.members, { name: memberName.trim(), role: "Assistant" }] } : expert)); setMemberName(""); setMemberOpen(false); }
  return <AdminShell platform><div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.12em] text-brand">EXPERTY · PLATFORM ADMIN</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.045em] text-ink-950">전문가 운영</h1><p className="mt-1 text-sm text-ink-500">전문가 페이지, 구독, 접근 권한을 한곳에서 관리합니다.</p></div><Dialog.Root open={newOpen} onOpenChange={setNewOpen}><Dialog.Trigger asChild><Button><Plus className="h-4 w-4" /> 전문가 추가</Button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[70] bg-ink-950/45 backdrop-blur-sm" /><Dialog.Content className="fixed left-1/2 top-1/2 z-[71] w-[calc(100%-2rem)] max-w-md -translate-x-1/2 -translate-y-1/2 rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><Dialog.Title className="text-xl font-bold">전문가 추가</Dialog.Title><Dialog.Description className="mt-1 text-sm text-ink-500">기본 전문가 페이지와 Owner 권한을 생성합니다.</Dialog.Description></div><Dialog.Close className="p-2 text-ink-400"><X className="h-5 w-5" /></Dialog.Close></div><label className="mt-6 block text-sm font-semibold">전문가 이름<input autoFocus value={expertName} onChange={(event) => setExpertName(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-line px-4 focus:outline-none focus:ring-2 focus:ring-brand" placeholder="예: 이진우" /></label><Button className="mt-6 w-full" onClick={addExpert}>전문가 생성</Button></Dialog.Content></Dialog.Portal></Dialog.Root></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="overflow-hidden rounded-3xl border border-line bg-white shadow-sm"><div className="flex items-center justify-between gap-3 border-b border-line p-5"><h2 className="font-bold text-ink-950">전문가 {experts.length}명</h2><label className="flex h-10 items-center gap-2 rounded-xl bg-surface px-3 text-ink-400"><Search className="h-4 w-4" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름 또는 분야 검색" className="w-36 bg-transparent text-sm text-ink-950 outline-none" /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="bg-surface text-xs text-ink-400"><tr><th className="px-5 py-3 font-semibold">전문가</th><th className="px-5 py-3 font-semibold">공개 도메인</th><th className="px-5 py-3 font-semibold">플랜</th><th className="px-5 py-3 font-semibold">문의</th><th className="px-5 py-3 font-semibold">상태</th><th className="px-5 py-3" /></tr></thead><tbody>{visible.map((expert) => <tr key={expert.id} onClick={() => setSelectedId(expert.id)} className={cn("cursor-pointer border-t border-line text-sm hover:bg-brand-50/50", expert.id === selected.id && "bg-brand-50")}><td className="px-5 py-4"><b className="block text-ink-950">{expert.name}</b><span className="text-xs text-ink-500">{expert.field}</span></td><td className="px-5 py-4 text-ink-500">{expert.domain}</td><td className="px-5 py-4"><span className="rounded-full border border-line bg-white px-2.5 py-1 text-xs font-bold text-ink-700">{expert.plan}</span></td><td className="px-5 py-4 font-bold text-ink-950">{expert.inquiries}건</td><td className="px-5 py-4"><span className={cn("rounded-full px-2.5 py-1 text-xs font-bold", statusClass[expert.status])}>{statusLabel[expert.status]}</span></td><td className="px-5 py-4 text-right"><MoreHorizontal className="inline h-5 w-5 text-ink-400" /></td></tr>)}</tbody></table></div></section>
      <aside className="rounded-3xl border border-line bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div><span className="text-xs font-bold text-brand">선택된 전문가</span><h2 className="mt-1 text-2xl font-bold text-ink-950">{selected.name}</h2><p className="mt-1 text-sm text-ink-500">{selected.field} · {selected.domain}</p></div><button onClick={() => setExperts((current) => current.map((expert) => expert.id === selected.id ? { ...expert, status: expert.status === "inactive" ? "active" : "inactive" } : expert))} className="rounded-lg bg-surface px-3 py-2 text-xs font-bold text-ink-500">{selected.status === "inactive" ? "활성화" : "비활성화"}</button></div><div className="mt-6 border-t border-line pt-5"><div className="flex items-center justify-between"><h3 className="font-bold text-ink-950">관리자 접근</h3><Dialog.Root open={memberOpen} onOpenChange={setMemberOpen}><Dialog.Trigger asChild><button className="inline-flex items-center gap-1 text-sm font-bold text-brand"><UserPlus className="h-4 w-4" /> 추가</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[70] bg-ink-950/45" /><Dialog.Content className="fixed left-1/2 top-1/2 z-[71] w-[calc(100%-2rem)] max-w-md -translate-x-1/2 -translate-y-1/2 rounded-3xl bg-white p-6 shadow-2xl"><Dialog.Title className="text-xl font-bold">Assistant 추가</Dialog.Title><Dialog.Description className="mt-1 text-sm text-ink-500">{selected.name}의 문의·일정 관리 접근 권한을 부여합니다.</Dialog.Description><input value={memberName} onChange={(event) => setMemberName(event.target.value)} className="mt-5 h-12 w-full rounded-xl border border-line px-4 focus:outline-none focus:ring-2 focus:ring-brand" placeholder="이름 또는 이메일" /><Button className="mt-4 w-full" onClick={addMember}>Assistant 추가</Button></Dialog.Content></Dialog.Portal></Dialog.Root></div><div className="mt-3 space-y-2">{selected.members.map((member) => <div key={`${member.name}-${member.role}`} className="flex items-center justify-between rounded-2xl bg-surface p-3"><span className="text-sm font-semibold text-ink-950">{member.name}</span><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-ink-500">{member.role}</span></div>)}</div></div><div className="mt-5 rounded-2xl bg-navy-900 p-4 text-white"><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="h-4 w-4 text-brand-soft" /> 권한 정책</div><p className="mt-2 text-xs leading-relaxed text-white/60">Owner는 홈페이지와 접근 권한을 관리하고, Assistant는 문의와 일정만 관리합니다.</p></div></aside></div></div></AdminShell>;
}
