"use client";

import { useState } from "react";
import { Check, ExternalLink, Plus, Save, Trash2 } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";
import { Button } from "@/components/ui/button";

const initialActivities = ["KBS 1라디오 갓생쇼 — 부동산 대토론회", "하반기 서울 아파트 시장 전망 기업 포럼", "저서 『서울 아파트 투자 지도』 개정판 출간"];

export default function ProfilePage() {
  const [activities, setActivities] = useState(initialActivities);
  const [saved, setSaved] = useState(false);
  const [newActivity, setNewActivity] = useState("");
  return <AdminShell><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.12em] text-brand">KIM INMAN · PUBLIC PAGE</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.045em] text-ink-950">홈페이지·활동 관리</h1><p className="mt-1 text-sm text-ink-500">공개 프로필과 섭외 담당자가 보는 최근 활동을 관리합니다.</p></div><a href="/kim-inman" target="_blank" className="inline-flex"><Button variant="outline" size="sm">공개 페이지 보기 <ExternalLink className="h-4 w-4" /></Button></a></div>
    <section className="mt-7 rounded-3xl border border-line bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-ink-950">기본 정보</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold text-ink-950">이름<input defaultValue="김인만" className="mt-2 h-12 w-full rounded-xl border border-line px-4 text-[15px] font-medium focus:outline-none focus:ring-2 focus:ring-brand" /></label><label className="text-sm font-semibold text-ink-950">직함<input defaultValue="부동산경제연구소장 · 부동산 시장 분석 전문가" className="mt-2 h-12 w-full rounded-xl border border-line px-4 text-[15px] focus:outline-none focus:ring-2 focus:ring-brand" /></label></div><label className="mt-5 block text-sm font-semibold text-ink-950">소개<textarea defaultValue="정부 정책·금리·세제가 서울과 수도권 아파트 가격에 미치는 영향을 현장에서 해석해 드립니다. 방송 출연과 기업 강연을 병행하고 있습니다." className="mt-2 min-h-28 w-full rounded-xl border border-line p-4 text-[15px] leading-relaxed focus:outline-none focus:ring-2 focus:ring-brand" /></label></section>
    <section className="mt-5 rounded-3xl border border-line bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-ink-950">최근 활동</h2><p className="mt-1 text-sm text-ink-500">등록한 순서대로 공개 페이지에 표시됩니다.</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold text-brand-deep">{activities.length}개 공개</span></div><div className="mt-5 space-y-2">{activities.map((activity, index) => <div key={activity} className="flex items-center gap-3 rounded-2xl border border-line p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-surface text-xs font-bold text-ink-500">{index + 1}</span><span className="flex-1 text-sm font-semibold text-ink-950">{activity}</span><button onClick={() => setActivities((current) => current.filter((item) => item !== activity))} className="rounded-lg p-2 text-ink-400 hover:bg-red-50 hover:text-red-600" aria-label="활동 삭제"><Trash2 className="h-4 w-4" /></button></div>)}</div><div className="mt-4 flex gap-2"><input value={newActivity} onChange={(event) => setNewActivity(event.target.value)} placeholder="활동 제목 또는 URL을 입력하세요" className="h-11 flex-1 rounded-xl border border-line px-4 text-sm focus:outline-none focus:ring-2 focus:ring-brand" /><Button size="sm" onClick={() => { if (newActivity.trim()) { setActivities((current) => [...current, newActivity.trim()]); setNewActivity(""); } }}><Plus className="h-4 w-4" /> 추가</Button></div></section>
    <div className="mt-6 flex items-center justify-end gap-3"><span className="text-sm font-semibold text-emerald-600">{saved && <><Check className="mr-1 inline h-4 w-4" />저장됨</>}</span><Button onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); }}><Save className="h-4 w-4" /> 변경사항 저장</Button></div></div></AdminShell>;
}
