"use client";

import { useState } from "react";
import { CheckCircle2, Copy, ExternalLink, Globe2, Link2, RefreshCw } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";
import { Button } from "@/components/ui/button";

export default function DomainPage() {
  const [domain, setDomain] = useState(""); const [requested, setRequested] = useState(false);
  return <AdminShell><div className="mx-auto max-w-3xl"><p className="text-xs font-bold tracking-[0.12em] text-brand">KIM INMAN · DOMAIN</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.045em] text-ink-950">도메인 연결</h1><p className="mt-1 text-sm text-ink-500">기본 전문가 주소와 원하는 커스텀 도메인의 연결 상태를 관리합니다.</p>
    <section className="mt-7 rounded-3xl bg-navy-900 p-6 text-white shadow-[0_20px_50px_rgba(16,24,40,.18)]"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-brand-soft">기본 서브도메인</span><h2 className="mt-4 text-2xl font-bold tracking-[-0.035em]">kim-inman.experty.kr</h2><p className="mt-2 text-sm text-white/60">Experty에서 자동으로 제공하는 공개 전문가 홈페이지 주소입니다.</p></div><span className="inline-flex items-center gap-1 rounded-full bg-emerald-400/15 px-3 py-1.5 text-xs font-bold text-emerald-300"><CheckCircle2 className="h-4 w-4" /> 연결됨</span></div><div className="mt-6 flex gap-2"><Button variant="white" size="sm" onClick={() => navigator.clipboard?.writeText("kim-inman.experty.kr")}><Copy className="h-4 w-4" /> 주소 복사</Button><a href="/kim-inman" target="_blank"><Button variant="ghost" size="sm" className="text-white hover:bg-white/10 hover:text-white">미리보기 <ExternalLink className="h-4 w-4" /></Button></a></div></section>
    <section className="mt-5 rounded-3xl border border-line bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-brand-100 text-brand"><Globe2 className="h-5 w-5" /></span><div><h2 className="text-lg font-bold text-ink-950">커스텀 도메인</h2><p className="text-sm text-ink-500">예: kim-inman.com · DNS 연결은 SaaS 출시 후 활성화됩니다.</p></div></div>{requested ? <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2 text-sm font-bold text-amber-700"><RefreshCw className="h-4 w-4" /> DNS 확인 대기 중</div><p className="mt-2 text-sm leading-relaxed text-amber-700/80">{domain}에 CNAME 레코드 `connect.experty.kr`를 추가하면 연결을 확인할 수 있습니다.</p></div> : <div className="mt-6 flex gap-2"><input value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="www.example.com" className="h-12 flex-1 rounded-xl border border-line px-4 text-[15px] focus:outline-none focus:ring-2 focus:ring-brand" /><Button onClick={() => domain.trim() && setRequested(true)}><Link2 className="h-4 w-4" /> 연결 요청</Button></div>}</section></div></AdminShell>;
}
